In [24]:
import numpy as np
from scipy.integrate import dblquad
from scipy.integrate import quad
import pandas as pd
from scipy.linalg import expm
from scipy.special import comb
from ilsmc.cutpoints import cutpoints_AB, cutpoints_ABC
from numba import njit
from ilsmc.get_emission_prob_mat import calc_emissions_single_JC69

In [49]:
mu = 0.0001

n_int_AB = 3
n_int_ABC = 3
coal_AB = 1
coal_ABC = 1
t_AB = 1
t_A = 1
mu_A = mu
t_B = 1
mu_B = mu
t_AB = 1
mu_AB = mu
t_C = t_A+t_AB
mu_C = mu
t_ABC = 1
mu_ABC = mu
t_upper = 10
t_peak = 2
mu_D = mu

In [50]:



n_markov_states = n_int_AB*n_int_ABC+n_int_ABC*3+3*comb(n_int_ABC, 2, exact = True)
cut_AB = cutpoints_AB(n_int_AB, t_AB, coal_AB)
cut_ABC = cutpoints_ABC(n_int_ABC, coal_ABC)
probs = np.empty((n_markov_states), dtype=object)
states = np.empty((n_markov_states), dtype=object)

acc = 0

for i in range(n_int_AB):
    for j in range(n_int_ABC):
        a0_a1_t_vec = [t_A, cut_AB[i]]
        a0_a1_mu_vec = [mu_A, mu_AB]
        b0_b1_t_vec = [t_B, cut_AB[i]]
        b0_b1_mu_vec = [mu_B, mu_AB]
        c0_c1_t_vec = [t_C, cut_ABC[j]]
        c0_c1_mu_vec = [mu_C, mu_ABC]
        ab0_ab1_t_vec = [t_AB-cut_AB[i+1], cut_ABC[j]]
        ab0_ab1_mu_vec = [mu_AB, mu_ABC]
        a1b1_ab0_t = cut_AB[i+1]-cut_AB[i]
        a1b1_ab0_mu = mu_AB
        ab1c1_abc0_t = cut_ABC[j+1]-cut_ABC[j] if j!=(n_int_ABC-1) else t_upper
        ab1c1_abc0_mu = mu_ABC


        add = t_upper+cut_ABC[n_int_ABC-1]-cut_ABC[j+1] if j!=(n_int_ABC-1) else 0
        d0_abc0_t_vec = [t_A+t_AB+cut_ABC[n_int_ABC-1]+t_upper]+[t_peak+add]
        d0_abc0_mu_vec = [mu_D, mu_ABC]
        
        print(i, j)
        for k in range(7):
            print(['a0_a1_t_vec', 'b0_b1_t_vec', 'a1b1_ab0_t', 'ab0_ab1_t_vec', 
              'ab1c1_abc0_t', 'c0_c1_t_vec', 'd0_abc0_t_vec'][k])
            print([a0_a1_t_vec, b0_b1_t_vec, a1b1_ab0_t, ab0_ab1_t_vec, 
              ab1c1_abc0_t, c0_c1_t_vec, d0_abc0_t_vec][k])
        print()
        
        emissions = calc_emissions_single_JC69(
            a0_a1_t_vec, b0_b1_t_vec, a1b1_ab0_t, ab0_ab1_t_vec, 
            ab1c1_abc0_t, c0_c1_t_vec, d0_abc0_t_vec,
            a0_a1_mu_vec, b0_b1_mu_vec, a1b1_ab0_mu, ab0_ab1_mu_vec, 
            ab1c1_abc0_mu, c0_c1_mu_vec, d0_abc0_mu_vec
        )
        states[acc] = (0, i, j)
        probs[acc] = emissions
        acc += 1

0 0
a0_a1_t_vec
[1, 0.0]
b0_b1_t_vec
[1, 0.0]
a1b1_ab0_t
0.2366174846098586
ab0_ab1_t_vec
[0.7633825153901415, 0.0]
ab1c1_abc0_t
0.4054651081081643
c0_c1_t_vec
[2, 0.0]
d0_abc0_t_vec
[13.09861228866811, 12.693147180559945]

0 1
a0_a1_t_vec
[1, 0.0]
b0_b1_t_vec
[1, 0.0]
a1b1_ab0_t
0.2366174846098586
ab0_ab1_t_vec
[0.7633825153901415, 0.4054651081081643]
ab1c1_abc0_t
0.6931471805599453
c0_c1_t_vec
[2, 0.4054651081081643]
d0_abc0_t_vec
[13.09861228866811, 12.0]

0 2
a0_a1_t_vec
[1, 0.0]
b0_b1_t_vec
[1, 0.0]
a1b1_ab0_t
0.2366174846098586
ab0_ab1_t_vec
[0.7633825153901415, 1.0986122886681096]
ab1c1_abc0_t
10
c0_c1_t_vec
[2, 1.0986122886681096]
d0_abc0_t_vec
[13.09861228866811, 2]

1 0
a0_a1_t_vec
[1, 0.2366174846098586]
b0_b1_t_vec
[1, 0.2366174846098586]
a1b1_ab0_t
0.3105500901261999
ab0_ab1_t_vec
[0.4528324252639415, 0.0]
ab1c1_abc0_t
0.4054651081081643
c0_c1_t_vec
[2, 0.0]
d0_abc0_t_vec
[13.09861228866811, 12.693147180559945]

1 1
a0_a1_t_vec
[1, 0.2366174846098586]
b0_b1_t_vec
[1, 0.236

In [48]:
cut_AB

array([0., 1.])

In [41]:
cut_ABC

array([0.        , 0.40546511, 1.09861229,        inf])

In [24]:
from ilsmc.optimizer import trans_emiss_calc
import numpy as np

In [32]:
N_AB = 5.266852e+04
N_ABC = 2.083065e+04
r = 6.373286e-09
t_1 = 1.570170e+05
t_2 = 3.970385e+04
t_upper = 8.327783e+05
n_int_AB = 1
n_int_ABC = 1
mu = 2e-8

tr, em, pi, hidden_names, observed_names = trans_emiss_calc(t_1, t_2, t_upper, N_AB, N_ABC, r, mu, n_int_AB, n_int_ABC)

tr

array([[9.99342139e-01, 2.19287048e-04, 2.19287048e-04, 2.19287048e-04],
       [7.40194780e-04, 9.97887519e-01, 6.86143339e-04, 6.86143339e-04],
       [7.40194780e-04, 6.86143339e-04, 9.97845370e-01, 7.28292193e-04],
       [7.40194780e-04, 6.86143339e-04, 7.28292193e-04, 9.97845370e-01]])

In [34]:
(2/3)*(np.exp(-t_2/(N_AB)))

0.31370282762094254

In [35]:
t_2/(N_AB)

0.7538440419438405

In [36]:
N_AB = 52206.80
N_ABC = 99998.37
t_1 = 156867.28
t_2 = 40142.80
t_upper = 753038.18
n_int_AB = 1
n_int_ABC = 1
mu = 2e-8
r = 1e-8

tr, em, pi, hidden_names, observed_names = trans_emiss_calc(t_1, t_2, t_upper, N_AB, N_ABC, r, mu, n_int_AB, n_int_ABC)

tr

array([[9.98988840e-01, 3.37053285e-04, 3.37053285e-04, 3.37053285e-04],
       [1.17034957e-03, 9.97626991e-01, 6.01329631e-04, 6.01329631e-04],
       [1.17034957e-03, 6.01329631e-04, 9.97560751e-01, 6.67569506e-04],
       [1.17034957e-03, 6.01329631e-04, 6.67569506e-04, 9.97560751e-01]])

In [38]:
(2/3)*(np.exp(-t_2/(N_AB)))

0.30900924003551505

In [39]:
t_2/(N_AB)

0.7689189913957569

In [51]:
N_AB = 50000
N_ABC = 50000
t_1 = 160000
t_2 = 40000
t_upper = 800000
n_int_AB = 1
n_int_ABC = 1
mu = 2e-8
r = 1e-8

tr, em, pi, hidden_names, observed_names = trans_emiss_calc(t_1, t_2, t_upper, N_AB, N_ABC, r, mu, n_int_AB, n_int_ABC)

tr

array([[9.99049576e-01, 3.16807993e-04, 3.16807993e-04, 3.16807993e-04],
       [1.16478348e-03, 9.97474205e-01, 6.80505551e-04, 6.80505551e-04],
       [1.16478348e-03, 6.80505551e-04, 9.97409325e-01, 7.45386384e-04],
       [1.16478348e-03, 6.80505551e-04, 7.45386384e-04, 9.97409325e-01]])

In [43]:
(2/3)*(np.exp(-t_2/(N_AB)))

0.29955264274481436

In [45]:
t_2/(N_AB)

0.8

In [52]:
N_AB = 50000
N_ABC = 100000
t_1 = 160000
t_2 = 40000
t_upper = 800000
n_int_AB = 1
n_int_ABC = 1
mu = 2e-8
r = 1e-8

tr, em, pi, hidden_names, observed_names = trans_emiss_calc(t_1, t_2, t_upper, N_AB, N_ABC, r, mu, n_int_AB, n_int_ABC)

tr

array([[9.99049576e-01, 3.16807993e-04, 3.16807993e-04, 3.16807993e-04],
       [1.16478348e-03, 9.97695615e-01, 5.69800789e-04, 5.69800789e-04],
       [1.16478348e-03, 5.69800789e-04, 9.97630722e-01, 6.34694092e-04],
       [1.16478348e-03, 5.69800789e-04, 6.34694092e-04, 9.97630722e-01]])